name: Deploy Admin to Firebase Hosting

on:
  push:
    branches:
      - main
    paths:
      - 'apps/admin/**'
      - 'packages/**'
      - 'firebase.json'
      - '.firebaserc'
      - 'pnpm-workspace.yaml'
      - 'pnpm-lock.yaml'
  pull_request:
    branches:
      - main
    paths:
      - 'apps/admin/**'
      - 'packages/**'
      - 'firebase.json'
      - '.firebaserc'
      - 'pnpm-workspace.yaml'
      - 'pnpm-lock.yaml'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.32.1

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22 # Usamos Node 22 acorde a tus engines actuales
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build Admin App
        run: pnpm --filter admin build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PET_U_FE87C }}
          projectId: pet-u-fe87c
          channelId: ${{ github.event_name == 'push' && 'live' || '' }}
